### ISSUE TITLE
Results from the best checkpoint or the last checkpoint?

### ISSUE THREAD

**Issue by siny1998** [Luffy03/Large-Scale-Medical#10]
Hi, excellent work!

Regarding the MSD datasets, I want to clarify if the results reported in the paper were based on the validation sets. Moreover, could you let me know which checkpoint was used for inference? Was it the checkpoint that achieved the best performance on the validation dataset or the one from the last epoch?

Thanks in advance!

**Comment by siny1998** [comment]
Hi, I reviewed the log file you provided and noticed that the paper’s results were based on the best performance on the validation set. Is that correct? This approach appears similar to using test data to select the checkpoint. Please let me know if I’ve misunderstood anything.

**Comment by Luffy03** [comment]
Hi, many thanks for your attention to our work and sorry for my late reply.
We report the results of suprem, unimiss, swin, voco ... (and so on) all from the best validation results in MONAI framework, since the original swinunetr used this approach thus we adopt it for fair comparisons. We save the best validation checkpoints to evaluate on some available testing leaderboards like https://codalab.lisn.upsaclay.fr/competitions/12239#results. While for the nnunet framework, both nnunet and voco-nnunet are reported by the last checkpooints for fair comparisons with nnunet.

**Comment by siny1998** [comment]
Thank you very much for your reply!

**Comment by Luffy03** [comment]
Thank you very much for your kind attention! Feel free to raise any issues if you have any other problems.
