### ISSUE TITLE
About inconsistency between dataset sizes specified in the json files and reported in the paper

### ISSUE THREAD

**Issue by jsadu826** [Luffy03/Large-Scale-Medical#24]
Hello, I wonder why there exists an inconsistency between dataset sizes in the following datasets. 

LIDC:
- **589** samples in _LIDC.json_, **1018** reported in paper

Tumor datasets:
- **1241** samples in _dataset_lits.json, dataset_panc.json, dataset_kits.json, healthy_ct_xxx.json_, **1334** reported in paper

PANORAMA:
- **2229** samples in _PANORAMA.json_, **2238 (actually 2235)** reported in paper

HeadNeckCT:
- **384** samples in _HeadNeckPet.json_, **504** reported in paper

TCGA-HNSC:
- **762** samples in _TCGA_HNSC.json_, **1274** reported in paper

![image](https://github.com/user-attachments/assets/2ac26120-9ac8-47ec-861a-f067c6332721)

**Comment by Luffy03** [comment]
Yes, the numbers reported in the paper are the original numbers. In the current version of the codes, we remove some cases since we find that when we use different versions of MONAI TO pre-cache the data "PersistentDataset", sometimes it will produce some broken files. So we remove these files to make sure the following researchers will not meet these bugs.
If you don't want to use "PersistentDataset", you can download the original datasets from their original links. And you need to change the json files as well.

**Comment by jsadu826** [comment]
Thanks for your great efforts! Btw, I have some confusions about the mechanism of monai PersistentDataset. Does the cache of a data file (.nii.gz) need to be recomputed only when the data transform is modified or the data file itself is modified? In these cases, will monai automatically identify and recomputed the cache?

**Comment by Luffy03** [comment]
Hi, only when the **data_path** of the data file is modified, monai will recompute the cache. In other cases, monai cannot idenrify it.
