### ISSUE TITLE
About the json file of the data split for the 5-fold cross validation

### ISSUE THREAD

**Issue by wangshansong1** [Luffy03/Large-Scale-Medical#26]
Could you please provide the json file of the data split for the 5-fold cross validation, as I found that the performance varies when using different data split json files, which may lead to unfair comparisons?

**Comment by Luffy03** [comment]
Thanks for your attention to our work. We did not conduct 5-fold validation for all of the datasets since most of them contain defined validation splits. For other datasets, we just use the splits defined by nnunet. If you want to compare with our methods, you can just use our json file or use our checkpoints for your splits.
