### ISSUE TITLE
Image Segmention

### ISSUE THREAD

**Issue by NirvanaChan** [Luffy03/Large-Scale-Medical#3]
Can I use this pre-trained model to segment unlabeled images? Does it support point prompts or text prompts？

**Comment by Luffy03** [comment]
Hi, thanks for your attention to our work and sorry for my late reply.
Sure you can use our models to segment unlabeled images, you can use the template as [test.py](https://github.com/Luffy03/Large-Scale-Medical/blob/main/Downstream/test.py) to predict the images, and the output format as [VoComni.json](https://github.com/Luffy03/Large-Scale-Medical/blob/main/VoComni/VoComni.json). But if you want to predict some specific types of tumors, I recommend you to finetune with some [downstream datasets](https://github.com/Luffy03/Large-Scale-Medical/tree/main/Downstream) since the pre-trainind models also need finetuning.
For point prompts or text prompts, I apologize for any confusion. This work is intended for backbone pretraining and is not compatible with SAM-based models, thus ours do not support prompts.

**Comment by Luffy03** [comment]
Hi, I would like to close this issue. Feel free to raise any issues if you have any other problems.
